title: Mohammed Adnan
email: mohd.adnan1306@gmail.com
url: "https://adnan1306.github.io"
baseurl: ""

author:
  name: Mohammed Adnan
  email: mohd.adnan1306@gmail.com
  photo: /assets/images/headshot.png
  scholar: https://scholar.google.com/citations?user=g39sWmYAAAAJ&hl=en
  github: https://github.com/adnan1306
  twitter: https://twitter.com/adnan_ahmad1306
  linkedin: https://www.linkedin.com/in/mohd-adnan-iitg

nav:
  - label: About
    url: /
  - label: Publications
    url: /publications/
  - label: CV
    url: /cv/
  - label: Photos
    url: /photos/

markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
